name: Run Scraper

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to scrape"
        required: true
      lazy:
        description: "Use lazy loading (true/false)"
        required: false
        default: "true"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install -r scraper/requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run scraper
        run: python scraper/playwright_scraper.py
        env:
          TARGET_URL: ${{ github.event.inputs.url }}
          USE_LAZY: ${{ github.event.inputs.lazy }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scraped-output
          path: output/
